### ISSUE TITLE
Not compatible with Minecraft 1.21.1

### ISSUE THREAD

**Issue by misuzu** [GeraldTM/MCProxyCommand#5]
**Describe the bug**
[Modrinth page](https://modrinth.com/plugin/proxy-command-reloaded ) says that Proxy Command Reloaded is compatible with Minecraft 1.21.x, but it not actually compatible with 1.21.1

**To Reproduce**
Start a fabric minecraft server 1.21.1 with a [latest version of Proxy Command Reloaded](https://modrinth.com/plugin/proxy-command-reloaded/versions?g=1.21.1&l=fabric)

**Expected behavior**
The server should start

**Additional context**
The log
```
[19:37:11] [main/INFO]: Loading Minecraft 1.21.1 with Fabric Loader 0.16.5
[19:37:11] [main/WARN]: Mod resolution failed
[19:37:11] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED proxy-command 1.1-1.21-34 {depends minecraft @ [1.21]}, ROOT_FORCELOAD_SINGLE proxy-command 1.1-1.21-34]
[19:37:11] [main/INFO]: Reason: [HARD_DEP proxy-command 1.1-1.21-34 {depends minecraft @ [1.21]}]
[19:37:11] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-model-loading-api-v1, fabric-keybindings-v0, fabric-renderer-registries-v1, fabric-client-tags-api-v1, fabric-sound-api-v1, fabric-rendering-v0, fabric-screen-api-v1, fabric-rendering-v1, fabric-key-binding-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1]
[19:37:11] [main/INFO]: Fix: add [], remove [], replace [[proxy-command 1.1-1.21-34] -> add:proxy-command 1 ([(-∞,∞)])]
[19:37:11] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
         - Replace mod 'ProxyCommand' (proxy-command) 1.1-1.21-34 with any version that is compatible with:
                 - minecraft 1.21.1
More details:
         - Mod 'ProxyCommand' (proxy-command) 1.1-1.21-34 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[ma1bspjw4klsqkqn4h0gbm09wvgl1w8b-fabric-server-launch.jar-fabric-0.16.5-1.21.1:9.6]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[ma1bspjw4klsqkqn4h0gbm09wvgl1w8b-fabric-server-launch.jar-fabric-0.16.5-1.21.1:9.6]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[ma1bspjw4klsqkqn4h0gbm09wvgl1w8b-fabric-server-launch.jar-fabric-0.16.5-1.21.1:9.6]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [ma1bspjw4klsqkqn4h0gbm09wvgl1w8b-fabric-server-launch.jar-fabric-0.16.5-1.21.1:9.6]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [ma1bspjw4klsqkqn4h0gbm09wvgl1w8b-fabric-server-launch.jar-fabric-0.16.5-1.21.1:9.6]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [ma1bspjw4klsqkqn4h0gbm09wvgl1w8b-fabric-server-launch.jar-fabric-0.16.5-1.21.1:9.6]
```

**Comment by GeraldTM** [comment]
Thanks for letting me know, I'll take a look asap. It might be a bit tho, I've got a lot on my plate atm

**Comment by misuzu** [comment]
> Thanks for letting me know, I'll take a look asap. It might be a bit tho, I've got a lot on my plate atm

No rush, please take care of yourself! Thank you!

**Comment by espartia** [comment]
You can fix this by changing "1.21" in fabric.mod.json to ["1.21", "1.21.\*"], but it might be possible to use just "1.21.\*".

**Comment by GeraldTM** [comment]
the latest version should be compatible with 1.21.1+
